### ISSUE TITLE
New-CMRequirementRule* docs are empty!

### ISSUE THREAD

**Issue by AndrzejWojtowicz** [MicrosoftDocs/sccm-docs-powershell-ref#198] opened 2020-10-09 10:02 UTC
When is the documentation for New-CMRequirementRule* cmdlets going to be released, it's kind of sad that it's already in production yet the docs do not provide examples or syntax....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d2b50ee-7b06-f5d0-03e2-885051234a41
* Version Independent ID: a75e595a-e6e4-4187-223b-96d709ef74f3
* Content: [New-CMRequirementRuleExpression (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmrequirementruleexpression?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMRequirementRuleExpression.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMRequirementRuleExpression.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2020-10-28 19:18
Dupe of #197

**Closed by aczechowski** 2020-10-28 19:18 UTC
Labels: duplicate
