### ISSUE TITLE
-LogonRequirementType  

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#162] opened 2020-04-16 04:58 UTC
I believe there is an additional accepted value for LogonRequirementType;
Accepted values:	WhereOrNotUserLoggedOn

There are three options and four accepted values

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd496a69-4a03-ebad-4b09-b6a8525e9a9b
* Version Independent ID: 1ab4c179-f1a7-386e-a6d1-f1711cbe2495
* Content: [Set-CMDeploymentType (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmdeploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2020-07-09 01:01
This is a duplicate of #146

**Closed by aczechowski** 2020-07-09 01:01 UTC
Labels: duplicate
