### ISSUE TITLE
New-CMPackageDeployment suggests to use deprecated cmdlet

### ISSUE THREAD

**Issue by jessiewestlake** [MicrosoftDocs/sccm-docs-powershell-ref#227] opened 2021-06-09 23:02 UTC
The notes in the description of `New-CMPackageDeployment` suggest to use `Start-CMPackageDeployment`, but the `Start-CMPackageDeployment` cmdlet outputs a warning that it has been deprecated and that `New-CMPackageDeployment` should be used instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabfb7b9-3081-8d55-263c-c6a21a1b995b
* Version Independent ID: a1f405c5-475d-af54-1733-0d3cb0e08fc4
* Content: [New-CMPackageDeployment (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmpackagedeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMPackageDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMPackageDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment] 2021-06-11 23:06
I'm going to close this one as a duplicate of #228, which also references Start-CMPackageDeployment as deprecated. I'll use that one to clean it up.

**Closed by aczechowski** 2021-06-11 23:06 UTC
Labels: duplicate
