### ISSUE TITLE
Output differs depending on parameter used

### ISSUE THREAD

**Issue by RicoRosenheim** [MicrosoftDocs/sccm-docs-powershell-ref#22] opened 2019-02-14 10:16 UTC
When using -Name parameter, the output if differs from the output you get when using -ResourceID. 
The output from -Name provides more info. of the type I need.
In particular I am using PowerShell to import devices by first looking for existing and duplicate device names (e.g. from AD disc) and conflicting MAC or SMBIOS GUIDs.
For this, I use WMI CIM query (no SCCM cmdlets for this type of query) but that only tells me if the device is obsolete, not if it's Approved and using the -Name parameter gives me all the computer names, include duplicate name devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bcbde8e-e5c1-26e8-00e4-c3e4a0283e48
* Version Independent ID: 221e6ea5-27a9-2ff3-849f-890d724c9242
* Content: [Get-CMDevice (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdevice?view=sccm-ps#required-parameters)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDevice.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDevice.md)

**Comment by FISHMANPET** [comment] 2019-05-13 14:14
It appears, based on warning output printed to the console, that calling Get-CMDevice with a resource ID will actually call get-CMResrouce under the hood.  Since Get-CMResource will get multiple types of resources, it probably doesn't have access to the same properties that get-cmdevice would.  Whether or not this is the best behavior is one thing, but at the very least the docs should call this out.

**Comment by aczechowski** [comment] 2020-12-28 22:59
Oh, I explained this when I recently revised this article! Look at the latest version, specifically the Description, and the Resource and CollectionMember parameters.
This behavior is by design. Closing this issue.

**Closed by aczechowski** 2020-12-28 22:59 UTC
